
GET http://localhost:5052/games

### 
GET http://localhost:5052/games/4

###
POST http://localhost:5052/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}


###
PUT http://localhost:5052/games/5
Content-Type: application/json

{
    "name": "Minecraft New World",
    "genre": "Kids and Family",
    "price": 24.99,
    "releaseDate": "2011-11-18"
}

###
DELETE http://localhost:5052/games/2